---
source: https://github.com/release-drafter/release-drafter/blob/master/.github/workflows/draft.yml
tags: ['github action', 'draft']
---

name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          